# Generated by Django 2.2.6 on 2019-10-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joketype',
            old_name='type',
            new_name='style',
        ),
    ]
