# Generated by Django 2.2.6 on 2019-10-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_auto_20191027_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joketype',
            old_name='style',
            new_name='type',
        ),
    ]
